dist: trusty
notifications:
  slack: ventureum-team:DSE8wxmLTenq0Yz17BrYBWg9
language: node_js
node_js:
- 8
fail_fast: true
deploy:
  - provider: s3
    cache_control: "max-age=0,no-cache,no-store,must-revalidate"
    access_key_id: $S3_ACCESS_KEY
    secret_access_key: $S3_SECRET
    bucket: www.chainsfr.com
    region: us-east-1
    acl: public_read
    on:
        branch: master
true:
  branch: master